services:
  development:
    build:
      context: .
      target: development
    image: react-tdd
    container_name: development
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - .:/usr/react-tdd
      - /usr/react-tdd/node_modules

  test:
    build:
      context: .
      target: development
    image: react-tdd
    container_name: test
    command: npm run test
    volumes:
      - .:/usr/react-tdd
      - /usr/react-tdd/node_modules
